name: tests

on:
  push:
    branches:
      - master
      - 10.x
  pull_request:
    branches:
      - master
      - 10.x

jobs:
  tests:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [7.2, 7.3, 7.4]
        typo3: [^10.4]

    name: P${{ matrix.php }} - T${{ matrix.typo3 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-typo3-${{ matrix.typo3 }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl
          coverage: none

      - name: Install dependencies
        run: composer require "typo3/minimal:${{ matrix.typo3 }}" --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Check PHP syntax errors
        run: find . -name \*.php ! -path "./.Build/*" -print0 | xargs -0 -n1 -P4 php -d display_errors=stderr -n -l > /dev/null

      - name: Execute unit tests
        run: .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/
        env:
          TYPO3_PATH_WEB: $PWD/.Build/public

      - name: Execute functional tests
        run: .Build/bin/phpunit --colors  -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml Tests/Functional/
        env:
          TYPO3_PATH_WEB: $PWD/.Build/public
          typo3DatabaseDriver: pdo_sqlite
